### ISSUE TITLE
Remove `consumer` column from SQLite results table?

### ISSUE THREAD

**Issue by JanCBrammer** [TUCAN-nest/SDF-pipeline#4]
The `consumer` column is potentially redundant. Removing it reduces the size of the SQLite files.

**Comment by idiotcommerce** [comment]
for removing column you can use alembic.

but i  think it is best for postgresql. but your is sqlite. that is the problem

**Comment by JanCBrammer** [comment]
Closing with aea619e1b2332a3c73c5404904d44a51edc979b5.
